// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABhRF9qOVQ4GUeIfItqZQPrqEOY5D1QII',
    appId: '1:140321630139:web:afd7c077342c5bba6c869e',
    messagingSenderId: '140321630139',
    projectId: 'revaglug-d8d5b',
    authDomain: 'revaglug-d8d5b.firebaseapp.com',
    storageBucket: 'revaglug-d8d5b.firebasestorage.app',
    measurementId: 'G-3580NZTJCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-kFv7hUSQYTo1RXs8SFOBwRUKslYcMj8',
    appId: '1:140321630139:android:f9a409c71d0a6a096c869e',
    messagingSenderId: '140321630139',
    projectId: 'revaglug-d8d5b',
    storageBucket: 'revaglug-d8d5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDz7JHl0fLr77DNK4zj3TN5_6Pc7A4cM',
    appId: '1:140321630139:ios:ce41a8db04e9cbda6c869e',
    messagingSenderId: '140321630139',
    projectId: 'revaglug-d8d5b',
    storageBucket: 'revaglug-d8d5b.firebasestorage.app',
    iosBundleId: 'com.example.revaGlug',
  );

}